### ISSUE TITLE
Uncompatible with OpenCV 3

### ISSUE THREAD

**Issue by cnpcshangbo** [cnpcshangbo/vision-hovering#2]
When I run 
```
python objtrack_fopd.py
```
I got the following errors.
```
root@intel-aero:~/vision-hovering-master/scripts# python objtrack_fopd.py 
>>> APM:Copter V3.6-dev (385d1c19)
>>> PX4: 8d505a02 NuttX: 1a99ba58
>>> Frame: QUAD
>>> AEROFCv1 003F0034 33355118 39343335
CherryPy Checker:
The Application mounted at '' has an empty config.

max in webserver:  14
Cherrypy initial completed.
Traceback (most recent call last):
  File "objtrack_fopd.py", line 583, in <module>
    strat.run()
  File "objtrack_fopd.py", line 239, in run
    fourcc = cv2.cv.CV_FOURCC(*'XVID')
AttributeError: 'module' object has no attribute 'cv'
```
After checking the cv version, I found the OpenCV on Intel Aero Drone is OpenCV 3. Then I remembered the main project of rmackay9/ardupilot-balloon-finder had a commit to make it compatible with OpenCV 3 (https://github.com/rmackay9/ardupilot-balloon-finder/commit/0dac5d6fac39ba5d5c15b75fb09ca89e540773b1). Therefore, I need to change according to it.

**Comment by cnpcshangbo** [comment]
After I made changes according to the commit, I got more errors.
```
root@intel-aero:~/vision-hovering-master/scripts# python objtrack_fopd.py 
>>> APM:Copter V3.6-dev (385d1c19)
>>> PX4: 8d505a02 NuttX: 1a99ba58
>>> Frame: QUAD
>>> AEROFCv1 003F0034 33355118 39343335
CherryPy Checker:
The Application mounted at '' has an empty config.

max in webserver:  14
Cherrypy initial completed.
Initialising camera.
started recording video to FOPD_1493697110.97.avi
VIDEOIO ERROR: libv4l unable to ioctl S_FMT
Floating point exception
```
